[package]
name = "r6_stratmaker_server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
tokio-websockets = { version = "0.13.3", features = [
    "server",
    "ring",
    "native-tls",
] }
futures-util = { version = "0.3.34", features = ["sink"] }
json = "0.12.4"
anyhow = "1.0.104"
fjall = "3.1.10"
uuid = { version = "1.26.0", features = ["v4", "serde"] }
serde_json = "1.0.151"
serde = { version = "1.0.229", features = ["derive"] }
bytesize = "2.7.0"
protobuf = "3.7"
# rkyv = { version = "0.8.18", features = ["unaligned"] }

[build-dependencies]
protobuf-codegen = "3.7"
