// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.3
//   protoc               v3.21.12
// source: primary.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

/** Shared types */
export interface Point {
  x: number;
  y: number;
}

export interface FreeDrawPath {
  points: Point[];
}

export interface StratFloor {
  freeDrawPaths: FreeDrawPath[];
}

export interface StratPhase {
  phaseName: string;
  floors: StratFloor[];
}

export interface StratState {
  stratName: string;
  phases: StratPhase[];
}

/** Hello */
export interface Hello {
}

export interface HelloResponse {
}

/** LoginRequest */
export interface LoginRequest {
  username: string;
}

export interface LoginResponse {
}

/** GetStratList */
export interface GetStratList {
}

export interface GetStratListResponseEntry {
  stratId: string;
  stratName: string;
  map: string;
}

export interface GetStratListResponse {
  strats: GetStratListResponseEntry[];
}

/** CreateEmptyStrat */
export interface CreateEmptyStrat {
  map: string;
}

export interface CreateEmptyStratResponse {
  stratId: string;
}

/** GetMapMetadata */
export interface GetMapMetadata {
  map: string;
}

export interface GetMapMetadataResponse {
  floors: string[];
}

/** GetStratInfo */
export interface GetStratInfo {
  stratId: string;
}

export interface GetStratInfoResponse {
  state: StratState | undefined;
}

/** SaveStrat */
export interface SaveStrat {
  stratId: string;
  state: StratState | undefined;
}

export interface SaveStratResponse {
}

export interface Client2Server {
  hello?: Hello | undefined;
  loginRequest?: LoginRequest | undefined;
  getStratList?: GetStratList | undefined;
  createEmptyStrat?: CreateEmptyStrat | undefined;
  getMapMetadata?: GetMapMetadata | undefined;
  getStratInfo?: GetStratInfo | undefined;
  saveStrat?: SaveStrat | undefined;
}

export interface Server2Client {
  helloResponse?: HelloResponse | undefined;
  loginResponse?: LoginResponse | undefined;
  getStratListResponse?: GetStratListResponse | undefined;
  createEmptyStratResponse?: CreateEmptyStratResponse | undefined;
  getMapMetadataResponse?: GetMapMetadataResponse | undefined;
  getStratInfoResponse?: GetStratInfoResponse | undefined;
  saveStratResponse?: SaveStratResponse | undefined;
}

function createBasePoint(): Point {
  return { x: 0, y: 0 };
}

export const Point: MessageFns<Point> = {
  encode(message: Point, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.x !== 0) {
      writer.uint32(13).float(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(21).float(message.y);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Point {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePoint();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 13) {
              break;
            }

            message.x = reader.float();
            continue;
          }
          case 2: {
            if (tag !== 21) {
              break;
            }

            message.y = reader.float();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Point {
    return {
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
    };
  },

  toJSON(message: Point): unknown {
    const obj: any = {};
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Point>, I>>(base?: I): Point {
    return Point.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Point>, I>>(object: I): Point {
    const message = createBasePoint();
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    return message;
  },
};

function createBaseFreeDrawPath(): FreeDrawPath {
  return { points: [] };
}

export const FreeDrawPath: MessageFns<FreeDrawPath> = {
  encode(message: FreeDrawPath, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.points) {
      Point.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FreeDrawPath {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseFreeDrawPath();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.points.push(Point.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): FreeDrawPath {
    return { points: globalThis.Array.isArray(object?.points) ? object.points.map((e: any) => Point.fromJSON(e)) : [] };
  },

  toJSON(message: FreeDrawPath): unknown {
    const obj: any = {};
    if (message.points?.length) {
      obj.points = message.points.map((e) => Point.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FreeDrawPath>, I>>(base?: I): FreeDrawPath {
    return FreeDrawPath.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FreeDrawPath>, I>>(object: I): FreeDrawPath {
    const message = createBaseFreeDrawPath();
    message.points = object.points?.map((e) => Point.fromPartial(e)) || [];
    return message;
  },
};

function createBaseStratFloor(): StratFloor {
  return { freeDrawPaths: [] };
}

export const StratFloor: MessageFns<StratFloor> = {
  encode(message: StratFloor, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.freeDrawPaths) {
      FreeDrawPath.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StratFloor {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseStratFloor();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.freeDrawPaths.push(FreeDrawPath.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): StratFloor {
    return {
      freeDrawPaths: globalThis.Array.isArray(object?.freeDrawPaths)
        ? object.freeDrawPaths.map((e: any) => FreeDrawPath.fromJSON(e))
        : [],
    };
  },

  toJSON(message: StratFloor): unknown {
    const obj: any = {};
    if (message.freeDrawPaths?.length) {
      obj.freeDrawPaths = message.freeDrawPaths.map((e) => FreeDrawPath.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StratFloor>, I>>(base?: I): StratFloor {
    return StratFloor.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StratFloor>, I>>(object: I): StratFloor {
    const message = createBaseStratFloor();
    message.freeDrawPaths = object.freeDrawPaths?.map((e) => FreeDrawPath.fromPartial(e)) || [];
    return message;
  },
};

function createBaseStratPhase(): StratPhase {
  return { phaseName: "", floors: [] };
}

export const StratPhase: MessageFns<StratPhase> = {
  encode(message: StratPhase, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.phaseName !== "") {
      writer.uint32(10).string(message.phaseName);
    }
    for (const v of message.floors) {
      StratFloor.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StratPhase {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseStratPhase();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.phaseName = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.floors.push(StratFloor.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): StratPhase {
    return {
      phaseName: isSet(object.phaseName)
        ? globalThis.String(object.phaseName)
        : isSet(object.phase_name)
        ? globalThis.String(object.phase_name)
        : "",
      floors: globalThis.Array.isArray(object?.floors) ? object.floors.map((e: any) => StratFloor.fromJSON(e)) : [],
    };
  },

  toJSON(message: StratPhase): unknown {
    const obj: any = {};
    if (message.phaseName !== "") {
      obj.phaseName = message.phaseName;
    }
    if (message.floors?.length) {
      obj.floors = message.floors.map((e) => StratFloor.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StratPhase>, I>>(base?: I): StratPhase {
    return StratPhase.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StratPhase>, I>>(object: I): StratPhase {
    const message = createBaseStratPhase();
    message.phaseName = object.phaseName ?? "";
    message.floors = object.floors?.map((e) => StratFloor.fromPartial(e)) || [];
    return message;
  },
};

function createBaseStratState(): StratState {
  return { stratName: "", phases: [] };
}

export const StratState: MessageFns<StratState> = {
  encode(message: StratState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stratName !== "") {
      writer.uint32(10).string(message.stratName);
    }
    for (const v of message.phases) {
      StratPhase.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StratState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseStratState();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.stratName = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.phases.push(StratPhase.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): StratState {
    return {
      stratName: isSet(object.stratName)
        ? globalThis.String(object.stratName)
        : isSet(object.strat_name)
        ? globalThis.String(object.strat_name)
        : "",
      phases: globalThis.Array.isArray(object?.phases) ? object.phases.map((e: any) => StratPhase.fromJSON(e)) : [],
    };
  },

  toJSON(message: StratState): unknown {
    const obj: any = {};
    if (message.stratName !== "") {
      obj.stratName = message.stratName;
    }
    if (message.phases?.length) {
      obj.phases = message.phases.map((e) => StratPhase.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StratState>, I>>(base?: I): StratState {
    return StratState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StratState>, I>>(object: I): StratState {
    const message = createBaseStratState();
    message.stratName = object.stratName ?? "";
    message.phases = object.phases?.map((e) => StratPhase.fromPartial(e)) || [];
    return message;
  },
};

function createBaseHello(): Hello {
  return {};
}

export const Hello: MessageFns<Hello> = {
  encode(_: Hello, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Hello {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseHello();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): Hello {
    return {};
  },

  toJSON(_: Hello): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Hello>, I>>(base?: I): Hello {
    return Hello.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Hello>, I>>(_: I): Hello {
    const message = createBaseHello();
    return message;
  },
};

function createBaseHelloResponse(): HelloResponse {
  return {};
}

export const HelloResponse: MessageFns<HelloResponse> = {
  encode(_: HelloResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HelloResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseHelloResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): HelloResponse {
    return {};
  },

  toJSON(_: HelloResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<HelloResponse>, I>>(base?: I): HelloResponse {
    return HelloResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HelloResponse>, I>>(_: I): HelloResponse {
    const message = createBaseHelloResponse();
    return message;
  },
};

function createBaseLoginRequest(): LoginRequest {
  return { username: "" };
}

export const LoginRequest: MessageFns<LoginRequest> = {
  encode(message: LoginRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseLoginRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.username = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): LoginRequest {
    return { username: isSet(object.username) ? globalThis.String(object.username) : "" };
  },

  toJSON(message: LoginRequest): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoginRequest>, I>>(base?: I): LoginRequest {
    return LoginRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginRequest>, I>>(object: I): LoginRequest {
    const message = createBaseLoginRequest();
    message.username = object.username ?? "";
    return message;
  },
};

function createBaseLoginResponse(): LoginResponse {
  return {};
}

export const LoginResponse: MessageFns<LoginResponse> = {
  encode(_: LoginResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseLoginResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): LoginResponse {
    return {};
  },

  toJSON(_: LoginResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<LoginResponse>, I>>(base?: I): LoginResponse {
    return LoginResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginResponse>, I>>(_: I): LoginResponse {
    const message = createBaseLoginResponse();
    return message;
  },
};

function createBaseGetStratList(): GetStratList {
  return {};
}

export const GetStratList: MessageFns<GetStratList> = {
  encode(_: GetStratList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStratList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGetStratList();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): GetStratList {
    return {};
  },

  toJSON(_: GetStratList): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetStratList>, I>>(base?: I): GetStratList {
    return GetStratList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetStratList>, I>>(_: I): GetStratList {
    const message = createBaseGetStratList();
    return message;
  },
};

function createBaseGetStratListResponseEntry(): GetStratListResponseEntry {
  return { stratId: "", stratName: "", map: "" };
}

export const GetStratListResponseEntry: MessageFns<GetStratListResponseEntry> = {
  encode(message: GetStratListResponseEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stratId !== "") {
      writer.uint32(10).string(message.stratId);
    }
    if (message.stratName !== "") {
      writer.uint32(18).string(message.stratName);
    }
    if (message.map !== "") {
      writer.uint32(26).string(message.map);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStratListResponseEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGetStratListResponseEntry();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.stratId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.stratName = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.map = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): GetStratListResponseEntry {
    return {
      stratId: isSet(object.stratId)
        ? globalThis.String(object.stratId)
        : isSet(object.strat_id)
        ? globalThis.String(object.strat_id)
        : "",
      stratName: isSet(object.stratName)
        ? globalThis.String(object.stratName)
        : isSet(object.strat_name)
        ? globalThis.String(object.strat_name)
        : "",
      map: isSet(object.map) ? globalThis.String(object.map) : "",
    };
  },

  toJSON(message: GetStratListResponseEntry): unknown {
    const obj: any = {};
    if (message.stratId !== "") {
      obj.stratId = message.stratId;
    }
    if (message.stratName !== "") {
      obj.stratName = message.stratName;
    }
    if (message.map !== "") {
      obj.map = message.map;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetStratListResponseEntry>, I>>(base?: I): GetStratListResponseEntry {
    return GetStratListResponseEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetStratListResponseEntry>, I>>(object: I): GetStratListResponseEntry {
    const message = createBaseGetStratListResponseEntry();
    message.stratId = object.stratId ?? "";
    message.stratName = object.stratName ?? "";
    message.map = object.map ?? "";
    return message;
  },
};

function createBaseGetStratListResponse(): GetStratListResponse {
  return { strats: [] };
}

export const GetStratListResponse: MessageFns<GetStratListResponse> = {
  encode(message: GetStratListResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.strats) {
      GetStratListResponseEntry.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStratListResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGetStratListResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.strats.push(GetStratListResponseEntry.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): GetStratListResponse {
    return {
      strats: globalThis.Array.isArray(object?.strats)
        ? object.strats.map((e: any) => GetStratListResponseEntry.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetStratListResponse): unknown {
    const obj: any = {};
    if (message.strats?.length) {
      obj.strats = message.strats.map((e) => GetStratListResponseEntry.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetStratListResponse>, I>>(base?: I): GetStratListResponse {
    return GetStratListResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetStratListResponse>, I>>(object: I): GetStratListResponse {
    const message = createBaseGetStratListResponse();
    message.strats = object.strats?.map((e) => GetStratListResponseEntry.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCreateEmptyStrat(): CreateEmptyStrat {
  return { map: "" };
}

export const CreateEmptyStrat: MessageFns<CreateEmptyStrat> = {
  encode(message: CreateEmptyStrat, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.map !== "") {
      writer.uint32(10).string(message.map);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateEmptyStrat {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCreateEmptyStrat();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.map = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): CreateEmptyStrat {
    return { map: isSet(object.map) ? globalThis.String(object.map) : "" };
  },

  toJSON(message: CreateEmptyStrat): unknown {
    const obj: any = {};
    if (message.map !== "") {
      obj.map = message.map;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateEmptyStrat>, I>>(base?: I): CreateEmptyStrat {
    return CreateEmptyStrat.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateEmptyStrat>, I>>(object: I): CreateEmptyStrat {
    const message = createBaseCreateEmptyStrat();
    message.map = object.map ?? "";
    return message;
  },
};

function createBaseCreateEmptyStratResponse(): CreateEmptyStratResponse {
  return { stratId: "" };
}

export const CreateEmptyStratResponse: MessageFns<CreateEmptyStratResponse> = {
  encode(message: CreateEmptyStratResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stratId !== "") {
      writer.uint32(10).string(message.stratId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateEmptyStratResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCreateEmptyStratResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.stratId = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): CreateEmptyStratResponse {
    return {
      stratId: isSet(object.stratId)
        ? globalThis.String(object.stratId)
        : isSet(object.strat_id)
        ? globalThis.String(object.strat_id)
        : "",
    };
  },

  toJSON(message: CreateEmptyStratResponse): unknown {
    const obj: any = {};
    if (message.stratId !== "") {
      obj.stratId = message.stratId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateEmptyStratResponse>, I>>(base?: I): CreateEmptyStratResponse {
    return CreateEmptyStratResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateEmptyStratResponse>, I>>(object: I): CreateEmptyStratResponse {
    const message = createBaseCreateEmptyStratResponse();
    message.stratId = object.stratId ?? "";
    return message;
  },
};

function createBaseGetMapMetadata(): GetMapMetadata {
  return { map: "" };
}

export const GetMapMetadata: MessageFns<GetMapMetadata> = {
  encode(message: GetMapMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.map !== "") {
      writer.uint32(10).string(message.map);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetMapMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGetMapMetadata();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.map = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): GetMapMetadata {
    return { map: isSet(object.map) ? globalThis.String(object.map) : "" };
  },

  toJSON(message: GetMapMetadata): unknown {
    const obj: any = {};
    if (message.map !== "") {
      obj.map = message.map;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetMapMetadata>, I>>(base?: I): GetMapMetadata {
    return GetMapMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetMapMetadata>, I>>(object: I): GetMapMetadata {
    const message = createBaseGetMapMetadata();
    message.map = object.map ?? "";
    return message;
  },
};

function createBaseGetMapMetadataResponse(): GetMapMetadataResponse {
  return { floors: [] };
}

export const GetMapMetadataResponse: MessageFns<GetMapMetadataResponse> = {
  encode(message: GetMapMetadataResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.floors) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetMapMetadataResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGetMapMetadataResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.floors.push(reader.string());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): GetMapMetadataResponse {
    return {
      floors: globalThis.Array.isArray(object?.floors) ? object.floors.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: GetMapMetadataResponse): unknown {
    const obj: any = {};
    if (message.floors?.length) {
      obj.floors = message.floors;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetMapMetadataResponse>, I>>(base?: I): GetMapMetadataResponse {
    return GetMapMetadataResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetMapMetadataResponse>, I>>(object: I): GetMapMetadataResponse {
    const message = createBaseGetMapMetadataResponse();
    message.floors = object.floors?.map((e) => e) || [];
    return message;
  },
};

function createBaseGetStratInfo(): GetStratInfo {
  return { stratId: "" };
}

export const GetStratInfo: MessageFns<GetStratInfo> = {
  encode(message: GetStratInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stratId !== "") {
      writer.uint32(10).string(message.stratId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStratInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGetStratInfo();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.stratId = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): GetStratInfo {
    return {
      stratId: isSet(object.stratId)
        ? globalThis.String(object.stratId)
        : isSet(object.strat_id)
        ? globalThis.String(object.strat_id)
        : "",
    };
  },

  toJSON(message: GetStratInfo): unknown {
    const obj: any = {};
    if (message.stratId !== "") {
      obj.stratId = message.stratId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetStratInfo>, I>>(base?: I): GetStratInfo {
    return GetStratInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetStratInfo>, I>>(object: I): GetStratInfo {
    const message = createBaseGetStratInfo();
    message.stratId = object.stratId ?? "";
    return message;
  },
};

function createBaseGetStratInfoResponse(): GetStratInfoResponse {
  return { state: undefined };
}

export const GetStratInfoResponse: MessageFns<GetStratInfoResponse> = {
  encode(message: GetStratInfoResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.state !== undefined) {
      StratState.encode(message.state, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStratInfoResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGetStratInfoResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.state = StratState.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): GetStratInfoResponse {
    return { state: isSet(object.state) ? StratState.fromJSON(object.state) : undefined };
  },

  toJSON(message: GetStratInfoResponse): unknown {
    const obj: any = {};
    if (message.state !== undefined) {
      obj.state = StratState.toJSON(message.state);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetStratInfoResponse>, I>>(base?: I): GetStratInfoResponse {
    return GetStratInfoResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetStratInfoResponse>, I>>(object: I): GetStratInfoResponse {
    const message = createBaseGetStratInfoResponse();
    message.state = (object.state !== undefined && object.state !== null)
      ? StratState.fromPartial(object.state)
      : undefined;
    return message;
  },
};

function createBaseSaveStrat(): SaveStrat {
  return { stratId: "", state: undefined };
}

export const SaveStrat: MessageFns<SaveStrat> = {
  encode(message: SaveStrat, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stratId !== "") {
      writer.uint32(10).string(message.stratId);
    }
    if (message.state !== undefined) {
      StratState.encode(message.state, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SaveStrat {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSaveStrat();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.stratId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.state = StratState.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): SaveStrat {
    return {
      stratId: isSet(object.stratId)
        ? globalThis.String(object.stratId)
        : isSet(object.strat_id)
        ? globalThis.String(object.strat_id)
        : "",
      state: isSet(object.state) ? StratState.fromJSON(object.state) : undefined,
    };
  },

  toJSON(message: SaveStrat): unknown {
    const obj: any = {};
    if (message.stratId !== "") {
      obj.stratId = message.stratId;
    }
    if (message.state !== undefined) {
      obj.state = StratState.toJSON(message.state);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SaveStrat>, I>>(base?: I): SaveStrat {
    return SaveStrat.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SaveStrat>, I>>(object: I): SaveStrat {
    const message = createBaseSaveStrat();
    message.stratId = object.stratId ?? "";
    message.state = (object.state !== undefined && object.state !== null)
      ? StratState.fromPartial(object.state)
      : undefined;
    return message;
  },
};

function createBaseSaveStratResponse(): SaveStratResponse {
  return {};
}

export const SaveStratResponse: MessageFns<SaveStratResponse> = {
  encode(_: SaveStratResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SaveStratResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseSaveStratResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): SaveStratResponse {
    return {};
  },

  toJSON(_: SaveStratResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SaveStratResponse>, I>>(base?: I): SaveStratResponse {
    return SaveStratResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SaveStratResponse>, I>>(_: I): SaveStratResponse {
    const message = createBaseSaveStratResponse();
    return message;
  },
};

function createBaseClient2Server(): Client2Server {
  return {
    hello: undefined,
    loginRequest: undefined,
    getStratList: undefined,
    createEmptyStrat: undefined,
    getMapMetadata: undefined,
    getStratInfo: undefined,
    saveStrat: undefined,
  };
}

export const Client2Server: MessageFns<Client2Server> = {
  encode(message: Client2Server, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hello !== undefined) {
      Hello.encode(message.hello, writer.uint32(10).fork()).join();
    }
    if (message.loginRequest !== undefined) {
      LoginRequest.encode(message.loginRequest, writer.uint32(18).fork()).join();
    }
    if (message.getStratList !== undefined) {
      GetStratList.encode(message.getStratList, writer.uint32(26).fork()).join();
    }
    if (message.createEmptyStrat !== undefined) {
      CreateEmptyStrat.encode(message.createEmptyStrat, writer.uint32(34).fork()).join();
    }
    if (message.getMapMetadata !== undefined) {
      GetMapMetadata.encode(message.getMapMetadata, writer.uint32(42).fork()).join();
    }
    if (message.getStratInfo !== undefined) {
      GetStratInfo.encode(message.getStratInfo, writer.uint32(50).fork()).join();
    }
    if (message.saveStrat !== undefined) {
      SaveStrat.encode(message.saveStrat, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Client2Server {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseClient2Server();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.hello = Hello.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.loginRequest = LoginRequest.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.getStratList = GetStratList.decode(reader, reader.uint32());
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.createEmptyStrat = CreateEmptyStrat.decode(reader, reader.uint32());
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.getMapMetadata = GetMapMetadata.decode(reader, reader.uint32());
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.getStratInfo = GetStratInfo.decode(reader, reader.uint32());
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.saveStrat = SaveStrat.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Client2Server {
    return {
      hello: isSet(object.hello) ? Hello.fromJSON(object.hello) : undefined,
      loginRequest: isSet(object.loginRequest) ? LoginRequest.fromJSON(object.loginRequest) : undefined,
      getStratList: isSet(object.getStratList) ? GetStratList.fromJSON(object.getStratList) : undefined,
      createEmptyStrat: isSet(object.createEmptyStrat) ? CreateEmptyStrat.fromJSON(object.createEmptyStrat) : undefined,
      getMapMetadata: isSet(object.getMapMetadata) ? GetMapMetadata.fromJSON(object.getMapMetadata) : undefined,
      getStratInfo: isSet(object.getStratInfo) ? GetStratInfo.fromJSON(object.getStratInfo) : undefined,
      saveStrat: isSet(object.saveStrat) ? SaveStrat.fromJSON(object.saveStrat) : undefined,
    };
  },

  toJSON(message: Client2Server): unknown {
    const obj: any = {};
    if (message.hello !== undefined) {
      obj.hello = Hello.toJSON(message.hello);
    }
    if (message.loginRequest !== undefined) {
      obj.loginRequest = LoginRequest.toJSON(message.loginRequest);
    }
    if (message.getStratList !== undefined) {
      obj.getStratList = GetStratList.toJSON(message.getStratList);
    }
    if (message.createEmptyStrat !== undefined) {
      obj.createEmptyStrat = CreateEmptyStrat.toJSON(message.createEmptyStrat);
    }
    if (message.getMapMetadata !== undefined) {
      obj.getMapMetadata = GetMapMetadata.toJSON(message.getMapMetadata);
    }
    if (message.getStratInfo !== undefined) {
      obj.getStratInfo = GetStratInfo.toJSON(message.getStratInfo);
    }
    if (message.saveStrat !== undefined) {
      obj.saveStrat = SaveStrat.toJSON(message.saveStrat);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Client2Server>, I>>(base?: I): Client2Server {
    return Client2Server.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Client2Server>, I>>(object: I): Client2Server {
    const message = createBaseClient2Server();
    message.hello = (object.hello !== undefined && object.hello !== null) ? Hello.fromPartial(object.hello) : undefined;
    message.loginRequest = (object.loginRequest !== undefined && object.loginRequest !== null)
      ? LoginRequest.fromPartial(object.loginRequest)
      : undefined;
    message.getStratList = (object.getStratList !== undefined && object.getStratList !== null)
      ? GetStratList.fromPartial(object.getStratList)
      : undefined;
    message.createEmptyStrat = (object.createEmptyStrat !== undefined && object.createEmptyStrat !== null)
      ? CreateEmptyStrat.fromPartial(object.createEmptyStrat)
      : undefined;
    message.getMapMetadata = (object.getMapMetadata !== undefined && object.getMapMetadata !== null)
      ? GetMapMetadata.fromPartial(object.getMapMetadata)
      : undefined;
    message.getStratInfo = (object.getStratInfo !== undefined && object.getStratInfo !== null)
      ? GetStratInfo.fromPartial(object.getStratInfo)
      : undefined;
    message.saveStrat = (object.saveStrat !== undefined && object.saveStrat !== null)
      ? SaveStrat.fromPartial(object.saveStrat)
      : undefined;
    return message;
  },
};

function createBaseServer2Client(): Server2Client {
  return {
    helloResponse: undefined,
    loginResponse: undefined,
    getStratListResponse: undefined,
    createEmptyStratResponse: undefined,
    getMapMetadataResponse: undefined,
    getStratInfoResponse: undefined,
    saveStratResponse: undefined,
  };
}

export const Server2Client: MessageFns<Server2Client> = {
  encode(message: Server2Client, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.helloResponse !== undefined) {
      HelloResponse.encode(message.helloResponse, writer.uint32(10).fork()).join();
    }
    if (message.loginResponse !== undefined) {
      LoginResponse.encode(message.loginResponse, writer.uint32(18).fork()).join();
    }
    if (message.getStratListResponse !== undefined) {
      GetStratListResponse.encode(message.getStratListResponse, writer.uint32(26).fork()).join();
    }
    if (message.createEmptyStratResponse !== undefined) {
      CreateEmptyStratResponse.encode(message.createEmptyStratResponse, writer.uint32(34).fork()).join();
    }
    if (message.getMapMetadataResponse !== undefined) {
      GetMapMetadataResponse.encode(message.getMapMetadataResponse, writer.uint32(42).fork()).join();
    }
    if (message.getStratInfoResponse !== undefined) {
      GetStratInfoResponse.encode(message.getStratInfoResponse, writer.uint32(50).fork()).join();
    }
    if (message.saveStratResponse !== undefined) {
      SaveStratResponse.encode(message.saveStratResponse, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Server2Client {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseServer2Client();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.helloResponse = HelloResponse.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.loginResponse = LoginResponse.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.getStratListResponse = GetStratListResponse.decode(reader, reader.uint32());
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.createEmptyStratResponse = CreateEmptyStratResponse.decode(reader, reader.uint32());
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.getMapMetadataResponse = GetMapMetadataResponse.decode(reader, reader.uint32());
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.getStratInfoResponse = GetStratInfoResponse.decode(reader, reader.uint32());
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.saveStratResponse = SaveStratResponse.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Server2Client {
    return {
      helloResponse: isSet(object.helloResponse) ? HelloResponse.fromJSON(object.helloResponse) : undefined,
      loginResponse: isSet(object.loginResponse) ? LoginResponse.fromJSON(object.loginResponse) : undefined,
      getStratListResponse: isSet(object.getStratListResponse)
        ? GetStratListResponse.fromJSON(object.getStratListResponse)
        : undefined,
      createEmptyStratResponse: isSet(object.createEmptyStratResponse)
        ? CreateEmptyStratResponse.fromJSON(object.createEmptyStratResponse)
        : undefined,
      getMapMetadataResponse: isSet(object.getMapMetadataResponse)
        ? GetMapMetadataResponse.fromJSON(object.getMapMetadataResponse)
        : undefined,
      getStratInfoResponse: isSet(object.getStratInfoResponse)
        ? GetStratInfoResponse.fromJSON(object.getStratInfoResponse)
        : undefined,
      saveStratResponse: isSet(object.saveStratResponse)
        ? SaveStratResponse.fromJSON(object.saveStratResponse)
        : undefined,
    };
  },

  toJSON(message: Server2Client): unknown {
    const obj: any = {};
    if (message.helloResponse !== undefined) {
      obj.helloResponse = HelloResponse.toJSON(message.helloResponse);
    }
    if (message.loginResponse !== undefined) {
      obj.loginResponse = LoginResponse.toJSON(message.loginResponse);
    }
    if (message.getStratListResponse !== undefined) {
      obj.getStratListResponse = GetStratListResponse.toJSON(message.getStratListResponse);
    }
    if (message.createEmptyStratResponse !== undefined) {
      obj.createEmptyStratResponse = CreateEmptyStratResponse.toJSON(message.createEmptyStratResponse);
    }
    if (message.getMapMetadataResponse !== undefined) {
      obj.getMapMetadataResponse = GetMapMetadataResponse.toJSON(message.getMapMetadataResponse);
    }
    if (message.getStratInfoResponse !== undefined) {
      obj.getStratInfoResponse = GetStratInfoResponse.toJSON(message.getStratInfoResponse);
    }
    if (message.saveStratResponse !== undefined) {
      obj.saveStratResponse = SaveStratResponse.toJSON(message.saveStratResponse);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Server2Client>, I>>(base?: I): Server2Client {
    return Server2Client.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Server2Client>, I>>(object: I): Server2Client {
    const message = createBaseServer2Client();
    message.helloResponse = (object.helloResponse !== undefined && object.helloResponse !== null)
      ? HelloResponse.fromPartial(object.helloResponse)
      : undefined;
    message.loginResponse = (object.loginResponse !== undefined && object.loginResponse !== null)
      ? LoginResponse.fromPartial(object.loginResponse)
      : undefined;
    message.getStratListResponse = (object.getStratListResponse !== undefined && object.getStratListResponse !== null)
      ? GetStratListResponse.fromPartial(object.getStratListResponse)
      : undefined;
    message.createEmptyStratResponse =
      (object.createEmptyStratResponse !== undefined && object.createEmptyStratResponse !== null)
        ? CreateEmptyStratResponse.fromPartial(object.createEmptyStratResponse)
        : undefined;
    message.getMapMetadataResponse =
      (object.getMapMetadataResponse !== undefined && object.getMapMetadataResponse !== null)
        ? GetMapMetadataResponse.fromPartial(object.getMapMetadataResponse)
        : undefined;
    message.getStratInfoResponse = (object.getStratInfoResponse !== undefined && object.getStratInfoResponse !== null)
      ? GetStratInfoResponse.fromPartial(object.getStratInfoResponse)
      : undefined;
    message.saveStratResponse = (object.saveStratResponse !== undefined && object.saveStratResponse !== null)
      ? SaveStratResponse.fromPartial(object.saveStratResponse)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
